# Generated by Django 5.2.8 on 2026-01-08 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(help_text='e.g., University of Oxford, Google, UNICEF', max_length=255)),
                ('location', models.CharField(help_text='e.g., Germany, USA, Remote', max_length=100)),
                ('country', models.CharField(default='Global', max_length=100)),
                ('opportunity_type', models.CharField(choices=[('Scholarship', 'Scholarship'), ('Internship', 'Internship'), ('Fellowship', 'Fellowship'), ('Conference', 'Conference')], default='Scholarship', max_length=20)),
                ('funding', models.CharField(choices=[('Fully Funded', 'Fully Funded'), ('Partial Funding', 'Partial Funding'), ('Stipend/Paid', 'Stipend/Paid')], default='Fully Funded', max_length=20)),
                ('description', models.TextField(help_text='General overview of the opportunity.')),
                ('benefits', models.TextField(help_text='What is covered? (e.g., Tuition, Monthly allowance, Airfare)')),
                ('eligibility', models.TextField(help_text='Who can apply? (e.g., Undergraduates, Specific nationalities, GPA)')),
                ('official_website', models.URLField(help_text="The official link to the organization's page")),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['deadline'],
            },
        ),
    ]
