# Generated by Django 5.2.8 on 2026-01-20 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_forumpost_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answervote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answervote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questionvote',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionvote',
            name='user',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_images/'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.resourcecategory'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='post_type',
            field=models.CharField(choices=[('Question', 'Question'), ('Problem', 'Technical Problem'), ('Expectation', 'Expectation'), ('Experience', 'Experience')], default='Question', max_length=20),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Enter tags separated by commas', max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='benefits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='eligibility',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='official_website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='organization',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Alumni',
        ),
        migrations.DeleteModel(
            name='AnswerVote',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
        migrations.DeleteModel(
            name='QuestionVote',
        ),
    ]
