# Generated by Django 5.2.8 on 2026-01-20 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_answervote_answer_remove_answervote_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_title', models.CharField(help_text='e.g., Senior Data Scientist', max_length=255)),
                ('current_company', models.CharField(help_text='e.g., Google', max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('location', models.CharField(help_text='e.g., Berlin, Germany', max_length=255)),
                ('graduation_year', models.PositiveIntegerField()),
                ('is_mentor', models.BooleanField(default=False)),
                ('mentorship_focus', models.CharField(blank=True, help_text='e.g., Scholarship Apps, Career Coaching', max_length=255)),
                ('monthly_slots', models.PositiveIntegerField(default=2)),
                ('bio_summary', models.TextField(help_text='A brief professional summary.')),
                ('has_success_story', models.BooleanField(default=False)),
                ('story_title', models.CharField(blank=True, max_length=255)),
                ('story_content', models.TextField(blank=True, help_text='The detailed journey and advice.')),
                ('linkedin_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Why do you want to connect with this mentor?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to='main.alumniprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
