# Generated by Django 6.0.2 on 2026-02-06 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aichatsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aichatsession',
            options={},
        ),
        migrations.AlterField(
            model_name='aichatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
