# Generated by Django 6.0.2 on 2026-02-07 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_aichatsession_options_alter_aichatsession_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mentorshiprequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answer_body',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='helpful_count',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='official_website',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='aichatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='bio_summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='current_company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='current_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='mentorship_focus',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='story_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='post_type',
            field=models.CharField(default='Question', max_length=20),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_mentorship_requests', to='main.alumniprofile'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_mentorship_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='funding',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.resourcecategory'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
