# Generated by Django 6.0.2 on 2026-02-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_answer_options_alter_mentorshiprequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='post_type',
            field=models.CharField(choices=[('Question', 'Question'), ('Discussion', 'Discussion'), ('Announcement', 'Announcement')], default='Question', max_length=20),
        ),
    ]
