# Generated by Django 6.0.2 on 2026-02-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(blank=True, help_text='University or organization logo/image', null=True, upload_to='opportunity_images/'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='url',
            field=models.URLField(blank=True, help_text='Link to official application page', max_length=500, null=True),
        ),
    ]
