# Generated by Django 6.0.2 on 2026-02-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_opportunity_image_opportunity_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='resourcecategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'Resource Categories'},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='resource',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('guide', '📘 Guide'), ('template', '📝 Template'), ('video', '🎥 Video'), ('article', '📄 Article'), ('course', '🎓 Course'), ('tool', '🛠️ Tool')], default='guide', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon (e.g., 📚)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='opportunity_images/'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='main.resourcecategory'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.forumcategory'),
        ),
    ]
