# Generated by Django 6.0.2 on 2026-02-17 01:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_forumcategory_alter_resource_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aichatsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='alumniprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-is_accepted', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'verbose_name_plural': 'Forum Categories'},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mentorshiprequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['deadline'], 'verbose_name': 'Opportunity', 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to='main.forumcategory'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='icon',
            field=models.CharField(default='📚', help_text='Emoji icon for the category (e.g., 📚, 🎓, ✍️)', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='main.role'),
        ),
    ]
