# Generated by Django 6.0.2 on 2026-03-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_aichatsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('general', 'General Field Opportunity'), ('edtech', 'EdTech Special Opportunity')], default='general', help_text='Select whether this is a General or EdTech Special opportunity', max_length=20),
        ),
    ]
